apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-network-policy
  namespace: db-ns
spec:
  podSelector:
    matchLabels:
      app: db
  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: auth-ns
        - namespaceSelector:
            matchLabels:
              name: api-ns
      ports:
        - protocol: TCP
          port: 5432