apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: data-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard