apiVersion: v1
kind: Secret
metadata:
    name: image-secret
    namespace: image-ns
type: Opaque
stringData:
    AUTH_SERVICE_URL: ENC[AES256_GCM,data:MRla2CtkqSSkfXv4KCabXVu4CmUggVXCgMVCnMh/QwjBvk/I5qf1Yog7oUzzkspgdLM=,iv:a2NiXlp3gSPwvQAnjEfOwfZMQLTlT3jbGYpVf4bOJ1g=,tag:/U8IVVQonKWS3OCIo/DOrQ==,type:str]
    MINIO_ENDPOINT: ENC[AES256_GCM,data:OO+QuUbQwf0+5vrMVywR1S4cKmCiP4MxhB7fCdTKgj0+9BXIOQ==,iv:CiLDam/kwCFn4/EKvyJP6hOCw1uxSxjWF4h3p8W2D8I=,tag:8R8XFXYhdJgvodWcv+cgyQ==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:O6prAQI=,iv:YTDXX+fL992eY6zsR2q4moNjIAYusBoZF5I0w3i0BQ0=,tag:OxjpcACG2BYBeCZRiQe59Q==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:pgNXdzGhqsY=,iv:K4CnwdfEGUeamqX+0KEW8FoGNtsxcid4+YsN8YzHsZw=,tag:24jiMhrQADaG7Hr9y+TEtA==,type:str]
    MINIO_BUCKET: ENC[AES256_GCM,data:b8xDgMtG,iv:U3IoKMLVTIRdMwM/8bBRAeodnWCWcdYAzp/XqXbmsaw=,tag:IGKss4e4UnZg8vPtdf19Ow==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:me-south-1:654654596998:key/132ebe15-2b4e-4fa5-8ecc-724d72c75f8d
          created_at: "2025-11-11T13:19:38Z"
          enc: AQICAHjQUujHgoHGyGnGSN7tFwJYiziJUxPjPhmJMzaOphsOOgHKLZXBZW825bTJF5ELyz6YAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMM6tqPg2QEiHcSUgyAgEQgDsNzia3KB6QStBXgHxG19E3IeIP7BbFOPh6TaRzlzEz2g4KBK/Czsd+e4+L+mqbTTNjIS8HHXpJVad3tA==
          aws_profile: ""
    lastmodified: "2025-11-11T13:19:38Z"
    mac: ENC[AES256_GCM,data:5TIZbxRpQiYp02pG/w7rxIlLuMlu6xhD7sqFdxwK8ZV+zL7ftNXRjt7IkW5xTek4DYsAWpCp5aZzW9K9dWVUF+tgp4lej6zfyap0z9SxcsukxeqtrvjleSpccbWNdZGvnUvKmNAwGdPgOlqFpr/jRDKl//VGcvLS+h65WTFlG2c=,iv:/C7KUYt13X0VinW6vGg66Id10LZI2pOJLDDa0ImMZQ4=,tag:2RLjINNFEEH0rUvSZIJCAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
