apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-network-policy
  namespace: ingress-ns
spec:
  podSelector:
    matchLabels:
      app: ingress-nginx
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from anywhere (external clients)
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
  egress:
    # Allow DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
    # Allow egress to api-service in api-ns
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: api-ns
        - podSelector:
            matchLabels:
              app: api
      ports:
        - protocol: TCP
          port: 3000
    # Allow egress to auth-service in auth-ns
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: auth-ns
        - podSelector:
            matchLabels:
              app: auth
      ports:
        - protocol: TCP
          port: 4000
    # Allow egress to image-service in image-ns
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: image-ns
        - podSelector:
            matchLabels:
              app: image
      ports:
        - protocol: TCP
          port: 5000