apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-network-policy
  namespace: api-ns
spec:
  podSelector:
    matchLabels:
      app: api
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-ns
        - namespaceSelector:
            matchLabels:
              name: auth-ns
      ports:
        - protocol: TCP
          port: 3000
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: auth-ns
        - namespaceSelector:
            matchLabels:
              name: db-ns
      ports:
        - protocol: TCP
          port: 4000
        - protocol: TCP
          port: 5432
  policyTypes:
    - Ingress
    - Egress