apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-network-policy
  namespace: api-ns
spec:
  podSelector:
    matchLabels:
      app: api
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-ns
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: auth-ns
      ports:
        - protocol: TCP
          port: 3000
  egress:
    # Allow DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
    # Allow traffic to auth and db services
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: auth-ns
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: db-ns
      ports:
        - protocol: TCP
          port: 4000
        - protocol: TCP
          port: 5432
  policyTypes:
    - Ingress
    - Egress