---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-regcred
  namespace: api-ns
spec:
  encryptedData:
    .dockerconfigjson: AgBfxQryNmeKDwWNsCJa6dTZnCfp4Ef80NYCHOI6qPM+lWOm6DhkOCYf3YbRy1a3FCAiIzhj+26xOoC9vSTbJPjNhoBW1jergnmIKbiUx9fyWvhx5rhHTc8fYJfE8Q6PddRkBTZClyXDwUaMurvA0eU8UZC/+x5+D+FxwtfGr9+60VlG87WRvCSz9ci3dQj0f6mSprK8Nopc6auUMU/+wjnFkYqnCe890jhSqXVCihdZDYjIWuTva09oSmCWXoF2AulXScs9sPX1deZY0SpvEpTFlfWe19Ytc6pvGssjTaAO+YPJ3uJ/S6vwv5Jt15ImGmPYydxA9ifzqWpkkOoAhBYhRBCVNo8qbezjxaBJ9LmCRGJ2DV724TqS8JlcBZ2esfC0XD4X/9xVdGfwhQK1PGcEMBp9nFnDeJWAsD1PmMV9sgt0NVAmoy20emA7INbaXdSr7w7eD44YnUhIURzhT+Gnut9zypgMM4uxVnxGW2znI9A3+C8gwY8xReRHkcZvEQx5GV9IeBvSJBAYg8vaiNkW1BdRmjbMOx9OF21F/qjOQljM3Myz7M6Fule+VCP6DpK2NWydMFYLalSirfCFrr5+hi+u6n6MD6AU26xkrhHf1Ukr6d/uHH2Tx+65YAkDbuDp8SHUlTUpJUzpW+kDPj14qVFGMz0QItvLTMO/cRbRvjpYfz8sfAU5BTGjxdvvI51km4ro71cPZX5JNP3L0cH5LsvI3SvlboMYiDDTXxsvfOiFvC5exJwM0zSvzvUaVwzSZpk4tgvEQw4DW6tmr6M5FLhU6Th9fEFHDjTgKNGwT39NqH5SoYlR7oMTzTKHvuAbrAMP+0X+RvIlcz4D5nto3puCnDMTGaw4OrE2OLIf53no9ebss/jP6wzryc3XvkiSuEShywwGU3Ay0N2ZNjpabIyRCK6LFQu/IqA64iGXB2ubnf2U0C4SPOzHfkKrx1UchTioqeEFZlDA1T3SmWIPDfjd1w==
  template:
    metadata:
      name: ghcr-regcred
      namespace: api-ns
    type: kubernetes.io/dockerconfigjson
