---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-regcred
  namespace: api-ns
spec:
  encryptedData:
    .dockerconfigjson: AgBSKnpt/MrZxnMVGBmS69369Wshj915aYVc94OrEn18ay1OT+q15td8ZzOCjkqPlNdkf46TlB4oEg2Flf0XEV/fWmdcj6oF2NWPaMkcut4ywFCuFkZAGgPRBBpDeXIwPW1lrp2yGqbSTfwmMy8fFfm0t97UPOgWqZdYUnr/VtzWG8orKv0YgyjZZKVrT9hViawjmMt9FUwcbxzsXrC9y0z1Gw6Cp5d4ksmiU3oimoruNOsGpALpB1wXmfX0eSq2FSFIQRFPsODdeO3b2fLKmVyE99dt7IMEfrHQt9TKUjnCbNbl2Afp1j/d64I5R7m5K1L/bitADRMG+89vxoZKDgX+oeLpd0TGICd2hzzcV75zrbZo5ToWrx+g8dn4/rw6vkKZSQ11E0pTY5j+LAWesJ+HDuqe4Sv4DiB1pYnlU2LEvIDWiAqcMXdGbfMKvyMPpZPdvseluxLTODd4PsmWj5k3Mah7mmbh6GrHPHg8KwKCO5jvQkE5LwkzKl9zaVBRz4yr8Hlq2Z4fjkrMxkC9GcTHg4CTmVsKHUaafk4eWOzPrCVvdGExV1ywyAMr26gHPWxy2HlwWm1wlugHdR3EvqBGiJq1sRGJqziB20xBHyTkDfVqMd5taNQx+EBJQpbKsko11+1Zh5PKZ6fWnF2DuRJn2+yEQc06PNa6U3aUP8jTADoouyfGOZKPxONmlGqUmyA4wX7ZjFbbchDMq7ikUssxfXWtAhgf0Ocs4CHt7AX7m+qIzVPTYj45RKbdSfOrWxKkzaJINWx2Bp1woIGsWP9P9VBOvER9BffkO4tl35Gk2Bcn4Y8q1der3dbzabiZ4MeuPTv8Z1LVC+J7wPyK8vkrU6Hrm7ihXBsE+epQXGWRUOF112I1IFOBZfrmO50AgoY4PVw94CxnowbLC774Ocsncl2nrW8fTY23GCj+xxdQ5yogF/E7P1m3WHXWcIfBK51TkBkTxHk3u/qgtLb74glsuVWvug==
  template:
    metadata:
      name: ghcr-regcred
      namespace: api-ns
    type: kubernetes.io/dockerconfigjson
