---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-secret
  namespace: auth-ns
spec:
  encryptedData:
    DATABASE_URL: AgBYCQraGsjs28Jy3UUbyXyaMdDq2W5U7aRAFJYPm/aP5ukLUafEHSZdqneVCM1r8H7tjMuRON3izf2t0KJ/k1c6iBjvDDZXElqxZZJbIA+iJlbMziHf2pqli8br67OpyFIv6PxDl47YEx0a63TXiOX3y6Z1ffRxK1y+BYu4weIG2RmTGs3cE4RKnmQQ1m32Ldyg53FNL46ZUubHwYig5B1R8U4//2XPezXDBpK60GYVZ6iCfwzlZFXNqXuLeDxJz0RAK+5mxITTmDBZ2yJQlK+kNprb4EzOQLPCPzGYb9abogb7Rdjb/TljU6zc/IihVW/ikrRg0NKyfwdD7F9hCDNtlOGcjSPjmnJxZkBGFg3Mql/oW6D6KsmWtwnWmBjxe2hKkWoXUMaSNx3lx5CBhQMx8txN9aKVa3d3Pa576WIOKsPtwDC35ALBXsLCr5C1/16/BEdOL+gwxZeCcyXppazcejLLjyV3Bxa1gYgfFlrTD3ohVCT/+1nLUA/lzo3DDYEHT0UOvtx8tDKdD1T6iVwMkcOt0GWmH8psdTK7X0yBM+qoEbFfCa9I11Bev3MpqD1cxWTHj10UFWQrPHNAJMPx8F7PmpXWRwAyGdS3S5Eafs7E8/iUjZs/zuu9GVMEZQ7XJBA2yhaNZOp4WbXAsZDmZ3c4qDb715VNEDF5L50fkq0yqMmCL44nj3DzPZW1ztQ46MDw3g+AsZvkCz29P60kwL2p8ZFu/vNwqNlDpRY3advNxJPu1zV0cI7CpPdZF+9kY2gmXkKV9k8TxGk7Cad/19nLCz+2Xo89NN1rpzSYIA==
    JWT_SECRET: AgBA/xuU5PvgP1kOOkzx/N7Ijxb8cvJ3DZip+pGRI/BU+z3jVtIzpFJi0HBC4nAU5BdEoc5vnm0DLW8L3acbIMDcpE5lh9Lbb5N5bhsfdCl8U85O9dRI5JFqLT71P4J2WHeSg2BPXnJHjaBritSWzWCbQlqtlf5Vp8lSs02USj9RVLT/+PTAgNWFeBrRyC9b8F5zzyTGWWfyGZjJqUCIjzH1ftTIfGfPBjwWgZFIuCWnZwndGmdtko4VkzvPeJEjcw8c5+K0VAqsc2NRJzjbIVhdoqL2yS3zFf3gFpIQktksPlDWX+renWJiuWMq0dA2K3GoTkFG2LgEN/hqyYfMHL40yXxWRwR3Kw4woh6fg3sHOZ/ZOcIaO6urCoN6ZMVDlhMBoJceCTzO7lltl9xuaaINDy+e9yRrjGRNaD6iXplMOeJvCd8N+OmJPTaF0prOCEThtIhj5ohLX+trkwbSPGOlXS0qb5jAJNIQ2cW1GCLO07rWyHjcP48jE3Ujrov0blhljaA88knRVUMYfaa5WS3nHyqqeXkf/Nb3E3oHReTKcS+72zf8qb5li+D65Q1IKcGZxfKuaYXVCGo4NZsxkgk29MkSTfdycvvuChXO1hO0LyGoDxMjqbMdL0jAwDEsEDg1XpRo0OWhCpLdW4JgLccIy+T0OOmnEE5t95MlN8DGj28K0rSgBJd+vYYBKyqiMST4B00S3Em1Ipqbh1+Tc0wyY2XyBSXit6UFI63RCBqlTpZ8PmQoXJxJNIvBTyWxZ/DKQd/O6dIQ6cYsbwvZLHsm
  template:
    metadata:
      name: auth-secret
      namespace: auth-ns
    type: Opaque
