apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init
  namespace: minio-ns
spec:
  template:
    spec:
      containers:
        - name: mc
          image: minio/mc:latest
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_PASSWORD
          command:
            - /bin/sh
            - -c
            - |
              mc alias set myminio http://minio.minio-ns.svc.cluster.local:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
              mc mb myminio/images --ignore-existing
              echo "Bucket 'images' created successfully"
      restartPolicy: OnFailure
  backoffLimit: 3
