apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: minio-network-policy
  namespace: minio-ns
spec:
  podSelector:
    matchLabels:
      app: minio
  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: image-ns
      ports:
        - protocol: TCP
          port: 9000   

  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53