---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
  namespace: minio-ns
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgB7Z7DGih60nvGInbxm5LnOsSMHKRtUKy07i3t5Vd6nB8VkU2FL5t6zcLlYiHSegRttzq7qH1jzfqa5fSpo79wu2UqHDAn+NHTfRwAzYdnux4aKVsFpyDQkE8o6t+nIFqSovYvrW7JjfPpw7AdrOmqaGPmgmKTLi7xG1xIiyFp5ndBjb9SlIHc+kvcBO+LZD4A/hLD3UR4GoRLBwU5Zaqb5AXffh5bSlx+8NhR2/SzTqXFpwdA9TntEZ0LkanfkASTAR4IaplIxvfcRmIFY7nqp/Y1ZoKSZt3jSJB3XDJ5FJI8w5io8c3SL7l+hS+A2FKnbBs605yBS0SWKnxwk2DPAa2r53Vu/LO0p+GAYcKHPH52aglk4uZfd78B00t4dnimlt6YrnLcpmPBII10hLO/cTkruJJOcwWQ4EuVgCuNUlCZ12Q4pIuJydBHuPwu+UcR/NHuKN4s6tEDefbuiKloD3K+vmI9EbIyOu//BhYQggYWra3R7rGRLBlKbw53IW7nx+IjKIzj76Ig+zyzo6Dk/Ef5GqD7JDPYEErWy5IHBXgQmOvEvW8fl4aKr//7GFSGQxpUTa0Z/vNpyYVEbUrecbDcXe19MOW2Zzn8U6KU2KbBL4+oHEQY988C2QwgFNfhDWFh4qw1wgkglkQ6Yh2/N6nBiaPMBXef1oqSVAnCgCLlfAULH2FL+RDU3O+mxkMuJtAWn6QKsrw==
    MINIO_ROOT_USER: AgChslE5obZW8wGaRIYbD0IsCcO9vN654daLjA854OStD2Xe+A2Ws/OPS63K0K7cR7vDTaBn35PiRv1ePIHA87D1+h4GCFNaU8t3ph9gz0+Sek558ln/OgxS4XAIpgLq2jE2ORD+tbAwdKDW2FxfbKMaSmbna05ftdmptlq+ciQnKRITkFgeJ7IlcXVR2YBBHHbS1cKCCx8Hx3zRbsR0Ck5NMS9PyWY/MgPu4+4+TI3wjqBc/+L/PcGFQEMUfIfuP0Z55+9eqgUL4ZQyRVLrJUz/1/dcqYuaQkfqbtNtzD7R+TPnGYcNEI457hUu4X0ydKoCQ0Oauwt6qSHWGmrr9Yye7PQx+pXKiL9zfOFTELoQ1DR2d4Bi18HVYSTNiOoKmahFplGslkXyTnJg5XsTZqvyBwrBTmEXXTs0ksP1voMfuJLNp8Ynatq2X4MGoprq7A/WDVt2KsdNacgOjGegVGBjAczu5fxMIkovOBfJzqn4jLf39bq7w8pUblW4O3nHMGidsUVjxHMYJwtgoqYpnKdjfJaZb9YLGeFAx89g2yPQ+cJg3e+MdrY5MqFt6wy+C0Wv7SBla7tc+JBeQzgP1lV+78y5p0mcp66Li7qVT9746tktlMi1sU1B4Gxb/Xi3hOGHY3vl7gGOjQO6ANHhW8x6HXVbjUOd7DnI1SK3z/FDBvJlXEw2zGXF2MzNZIqEsY1a0+ZIPA==
  template:
    metadata:
      name: minio-secret
      namespace: minio-ns
    type: Opaque
