---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
  namespace: minio-ns
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgCZFfdrYPpLy6AJVSi5aHHq2sK63xAajz3vK2olQMqGY5bsOyDECTZkx4dZQp/Ledy+zk+pymJKaWJQdc/8oW9W6C+1ucevDxq22AVt4JrrV+iPXBGwck5B+mO2AuVZplSktPNdRXZ6NFzc38yWIIhai8e0kDdGSwO5WLIo9UYFIeOcoKUlZaKKIg3QhX3Fejl3i0umwq+1duI4Uk7hprd/wTMU+KYttSJLEFPZRe19+In324j+iJFfA3YePNNqGOg1FmAi2IULBym3G3EisHYCX95HakoZmb9oaBsy7JjIK0msCcDbmbBB6U4Qd9h51hc7rpcAWrLnsIuSu4XLDrnlPudFkSgFZgiNNmZdqxFLejZ+FEQvCafiQcru8/txorQoGugqAeOmhqruABl4JO6rHR+wy0/0TmMhOohAF2tiKhtEPG3inGn8/OvkERT/mTD4xNiXwoeNtCUppFILOvYsR5YQdJgVgbJg0w454t1L0h4L8iCsWNLAfL6zhSH7Sajgj/OBe5271ZVYfESCRlNiMc2kCzJxhAqkkurzuqwdzztx4LFlnf46v6h1BVu4N/cgWnvUPRxZYJi/q7QPKpdCr+yeEjvUsNuMq0st7blWfAGwk8I3pcVswV0yeo9R8aapo1MXjqB4CLUYt4RHvM01CyFjE6vIQXudsjg7q19D5FmJHB+gohhF/WHijluqi8KB3UVLPEIbKcYK
    MINIO_ROOT_USER: AgDRH5jvgJvDA78p/06QIXSHPH2yWZRdIQf7plc9tZsqRiVBBf7tbyVyif379gUYWfst6CHgEyWRTuGOW2b8F3oGP5P/Zi2mkr3jWKYr5xW+JMzR91E4dKsKvW41Cof7gXBt9KO9t22Iuov3RlyeD3L2jkBZQGxHI/xms1Do/raTFkkWrYyD3UWqzKlPfQYcuq+sqAj7qjf8gm64CkNKYIzKN1+vMupeVSzYwq9Pw1n17yYIcVFEncJqaGUEh0eJnq7wDFOpfhEHRJGZvURP4qs2MzMeCzE9jTMVlx5n2sxCeSa4+vJDF9fvyidKPXav14R+yWnwTbKuQ+SPA2RfZl976x/5iRBalovwM0kMNYgFVV8LlHZ3hRwZmkTI8FoxrizxpYlSmXMTH+yTMhhHoKsL4yF92a3RPxRvXKT6R631HU6zL7V3s/e1EXmkGvqC66brl3Fv7yjj+dix47RbECx8biNYTN33zFq13EBx3r9/LUjz4sMTRhmIGaWHo0Wye2jLZvgQOvcwQuO8XnhGzl9hjy8OFfat4LTPXEC0BTD/e4xfJ8tDrVtb8JbaPtZ8o4QrYP3bcRyd40WiHdgH5BMxsraPSjAtWBWitOlK+bPfu12tk7C97OpqN6407tiYoZ8MZp+YVK+skQn4GB/HSAgRs3vKX0xp7Si1atuKFTZt61/5VM/jeGNt/RQ5B/J7sPz0+jv7DW4OY+7M
  template:
    metadata:
      name: minio-secret
      namespace: minio-ns
