apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      initContainers:
      - name: install-sops
        image: alpine:3.18
        command:
        - sh
        - -c
        - |
          wget -O /custom-tools/sops https://github.com/getsops/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64
          chmod +x /custom-tools/sops
        volumeMounts:
        - name: custom-tools
          mountPath: /custom-tools
      containers:
      - name: argocd-repo-server
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_DEFAULT_REGION
        - name: XDG_CONFIG_HOME
          value: /.config
        - name: SOPS_AGE_KEY_FILE
          value: /.config/sops/age/keys.txt
        volumeMounts:
        - name: custom-tools
          mountPath: /usr/local/bin/sops
          subPath: sops
      volumes:
      - name: custom-tools
        emptyDir: {}
